apiVersion: v1
kind: Service
metadata:
  name: qr-code-component-main
  namespace: default
spec:
  selector:
    app: qr-code-component-main-app
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
